apiVersion: v1
kind: Service
metadata:
  labels:
    app: default-http-backend
  name: my-ingress
  namespace: ingress-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: default-http-backend
  type: LoadBalancer
