# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.base_mac = nil

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = "2"
    vb.linked_clone = true
  end

  (1..2).each do |i|
    config.vm.define "rke0#{i}" do |node|
      node.vm.hostname = "rke0#{i}"
      node.vm.network "private_network", ip: "192.168.111.10#{i}"
      node.vm.provider "virtualbox" do |vb|
        vb.name = "rke0#{i}"
      end
      node.vm.provision "shell" do |s|
        s.inline = <<-EOT
          echo "$1  $2" >>/etc/hosts
          EOT
        s.args   = [ "192.168.111.10#{i}", "rke0#{i}" ]
      end
    end
  end

  # config.vm.define "rke01" do |node|
  #   node.vm.hostname = "rke01"
  #   node.vm.network "private_network", ip: "192.168.111.101"
  #   node.vm.provider "virtualbox" do |vb|
  #     vb.name = "rke01"
  #   end
  # end

  # config.vm.define "rke02" do |node|
  #   node.vm.hostname = "rke02"
  #   node.vm.network "private_network", ip: "192.168.111.102"
  #   node.vm.provider "virtualbox" do |vb|
  #     vb.name = "rke02"
  #   end
  # end

  config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
  config.vm.provision "shell", inline: <<-EOT
    cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    EOT

  config.vm.provision "shell", name: "rke-setup", path: "rke-node-setup.sh"

end
